name: Deploy Angular App to AWS ECS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: private

    - name: Build Docker image
      run: |
        docker build -t meal-recommendation .

    - name: Tag Docker image
      run: |
        docker tag meal-recommendation:latest 340752798287.dkr.ecr.ap-south-1.amazonaws.com/meal-recommendation:latest

    - name: Push to ECR
      run: |
        docker push 340752798287.dkr.ecr.ap-south-1.amazonaws.com/meal-recommendation:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster mealrecommendation --service mealrecommendation-ui --force-new-deployment
